### ISSUE TITLE
How to limit the amount of deformation?

### ISSUE THREAD

**Issue by r03ert0** [ecr05/MSM_HOCR_macOSX#2]
Hello!
Thank you for MSM : )
I'm working with the version that comes with FSL, and although it often works very nicely, sometimes there are regions that get veery large deformations. Is there a way of limiting the maximum amount of deformation allowed? I tried lowering down the lambdas, from 0,0.1,0.2,0.3 to 0,0.01,0.02,0.03, but I still get the very large deformations... Would this improve if I move to msm_hocr?

**Comment by ecr05** [comment]
Hi Roberto,

You must increase regularisation, not decrease. Not knowing your data it is
difficult to be confident in what values to suggest, but try running
0,0.3,0.4,0.5. Generally I optimise by running one resolution level at a
time using the --levels parameter so run --levels=2 (as 2 is your first
discrete level) with different regularisation parameters for the second
level i.e. currently its 0.1, try 0.2, 0.3, 0.4 ... 0.5  then move onto the
third level.

The regularisation in msm_hocr is much more robust, and will lead to better
alignment with lower distortions, particularly for noisy data such as fMRI.
However, if you are just working with folding patterns I think the FSL
version will work well for you  - just increase the regularisation
somewhat. Note, the optimisation used in the FSL version means it is also
much faster to run.

Let me know if you need more help

Thanks

Emma

**Comment by r03ert0** [comment]
now it works much better : )

I'm registering brains of ferrets. I have a small one and a larger one. The code I use to generate the spheres makes spheres which keep the original mesh volume (i don't remember why...). Is it a problem if the two spheres have different sizes? Could this add to the distorsion?

**Comment by ecr05** [comment]
I'm fairly sure msm rescales the spheres to have same radius. You can check
the output?

**Comment by r03ert0** [comment]
(is it ok to post issue about MSM here or should I better use the FSL
e-mail forum?)

**Comment by ecr05** [comment]
Yes, of course. It is easier for me as I do not yet have a filter on the
FSL list for MSM emails and so might miss them.

Longer term I should move to the FSL list as that way everyone will see and
be able to search for the responses, but until there is sufficient critical
mass, this route is fine.

**Comment by r03ert0** [comment]
cool : )
I'll go and close this issue, because you already answered how to minimise deformation (by using larger lambda values, not smaller one)
