### ISSUE TITLE
About the usage of MSM_strain

### ISSUE THREAD

**Issue by ruoyu-z** [ecr05/MSM_HOCR_macOSX#26]
Hi,
In my thesis I want to compare MSM_strain. so I want to know how to use MSM_strain. the way I understand how to use it is as follows: 
1. download the executable file https://github.com/ecr05/MSM_HOCR/releases
2. specify the config file as config/basic_configs/config_standard_MSM_strain when running the msm command
Like this: msm_ubuntu_v3 --inmesh= --indata= --refdata= --conf=config_standard_MSM_strain -o  
3. If I am using the HCP dataset, and only using sulc, select the configuration file config/HCP_multimodal_alignment/MSMSulcStrainFinalconf

This is my idea, is this correct please? 

Also, I would like to know what the MSMAllStrainFinalconf1to1_1to3_1 and the
MSMAllStrainFinalconf1to1_1to3_2 are the profiles for what application.

I hope I am not disturbing you.I'd appreciate it if you could answer my questions. 

Look forward to your early reply.

**Comment by ecr05** [comment]
Hi Renato

Can you handle this.

Emma



Dr Emma C. Robinson

https://metrics-lab.github.io/


Apologies if you get emails outside normal work hours - I have small children and work flexibly. I don't expect a reply at these times.


Senior Lecturer In Medical Image Computing

School of Biomedical Engineering and Imaging Sciences

Kings College London


Office: 5th floor, Becket House, 1 Lambeth Palace Road, London SE1 7EU, UK
Mail: 4th Floor, Lambeth Wing, St Thomas' Hospital, London SE1 7EH
Tel. +44 (0)20 784 89557
________________________________
From: zhang ruoyu ***@***.***>
Sent: Friday, June 14, 2024 4:28 PM
To: ecr05/MSM_HOCR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ecr05/MSM_HOCR] About the usage of MSM_strain (Issue #26)


Hi,
In my thesis I want to compare MSM_strain. so I want to know how to use MSM_strain. the way I understand how to use it is as follows:

  1.  download the executable file https://github.com/ecr05/MSM_HOCR/releases
  2.  specify the config file as config/basic_configs/config_standard_MSM_strain when running the msm command
Like this: msm_ubuntu_v3 --inmesh= --indata= --refdata= --conf=config_standard_MSM_strain -o
  3.  If I am using the HCP dataset, and only using sulc, select the configuration file config/HCP_multimodal_alignment/MSMSulcStrainFinalconf

This is my idea, is this correct please?

Also, I would like to know what the MSMAllStrainFinalconf1to1_1to3_1 and the
MSMAllStrainFinalconf1to1_1to3_2 are the profiles for what application.

I hope I am not disturbing you.I'd appreciate it if you could answer my questions.

Look forward to your early reply.

**Comment by ruoyu-z** [comment]
Sorry, I don't understand, did you send the wrong email?

**Comment by ecr05** [comment]
I forwarded it to my software engineer



Dr Emma C. Robinson

https://metrics-lab.github.io/


Apologies if you get emails outside normal work hours - I have small children and work flexibly. I don't expect a reply at these times.


Senior Lecturer In Medical Image Computing

School of Biomedical Engineering and Imaging Sciences

Kings College London


Office: 5th floor, Becket House, 1 Lambeth Palace Road, London SE1 7EU, UK
Mail: 4th Floor, Lambeth Wing, St Thomas' Hospital, London SE1 7EH
Tel. +44 (0)20 784 89557
________________________________

**Comment by ruoyu-z** [comment]
Thank you for the clarification. I will wait for Renato's response. Please let me know if there is any additional information I should provide to assist with my query.

**Comment by rbesenczi** [comment]
Hi,
Yes that is one possible use case. If you tell us what you are about to do, I'm sure we can help you. 

The MSMAllStrainFinalconf1to1_1to3_1 files are for MSMAll in the HCP pipeline's multimodal alignment, see: https://github.com/Washington-University/HCPpipelines/tree/master/MSMAll

Please also note, that now we have a new, reworked version of MSM that runs a bit faster than the one you use. See instructions here: https://metrics-lab.github.io/newMSM/

**Comment by ruoyu-z** [comment]
Thanks for the reply.@rbesenczi 
I will describe in detail what I want to do.

I am conducting a comparative experiment on cortical surface registration (using only sulc features), where the two methods being compared are MSM_pair and MSM_strain. I am using the HCP S1200 dataset, and the goal is to register the unregistered surface files (native) in the dataset to the atlas (MSMSulc.L.refsulc.164k_fs_LR.shape.gii).

**1.Data Preprocessing:**

**Moving Image:** First, I downloaded the subjectID.L.sulc.ico6.shape.gii and subjectID.L.sphere.native.surf.gii for each subject ID from HCP.
**Fixed Image:** MSMSulc.L.refsulc.164k_fs_LR.shape.gii and fsaverage.L_LR.spherical_std.164k_fs_LR.surf.gii

I resampled both the moving_image and fixed_image to the average 32k surface of the HCP dataset (S1200.L.sphere.32k_fs_LR.surf.gii) to obtain new shape.gii files: subjectID.L.sulc.32k.shape.gii and S1200.L.refsulc.32k_fs_LR.shape.gii.

**2.Running the MSM Command:**
msm_ubuntu_v3 --inmesh=S1200.L.sphere.32k_fs_LR.surf.gii --indata=subjectID.L.sulc.32k.shape.gii --refdata=S1200.L.refsulc.32k_fs_LR.shape.gii --conf=MSMSulcStrainFinalconf.txt -o ~/msm_test_strain/subjectID.L.

Are there any unreasonable steps in the above procedure? I resampled the data to 32k because the FSLMSM website indicates that MSM performs well at 32k. One question that confuses me is the different versions of MSM, such as MSM_pair, MSM_strain, and MSM_HOCR. Are they simply different configuration file settings while the executable file remains the same? Can I use the newmsm mentioned in your reply to run all of them?

Look forward to your early reply.

**Comment by rbesenczi** [comment]
Hi @Git-zry,

Sorry for the delayed reply, we were super busy in the recent weeks.
Your experiment sounds very interesting, and I think the steps you propose are reasonable.

If you downloaded the binary from here, the different versions are coming from using MSM with different configuration files. MSM_strain and MSM_HOCR has an better regularisation method. 

You can also try newMSM, although it is still in development for a few months. Essentially it is a reimplementation of MSM with improved efficiency, negligible differences in results.

**Comment by ruoyu-z** [comment]
Thanks for your reply, it was very helpful!
