### ISSUE TITLE
config_file for neonatal data

### ISSUE THREAD

**Issue by trichtu** [ecr05/MSM_HOCR_macOSX#27]
Hi, in the README.txt, there says a config_strain_STRAIN_SPHERE_shear20_within file when using MSM for neonatal data, but I could not find it? Could you tell where it is?

**Comment by trichtu** [comment]
And infant template you provide in the https://brain-development.org/brain-atlases/atlases-from-the-dhcp-project/cortical-surface-atlas-bozek/ could not be downloaded. It is forbidden when download it. Could you fix this link?

**Comment by ecr05** [comment]
It's this one https://github.com/ecr05/dHCP_template_alignment/blob/master/configs/config_subject_to_40_week_template_3rd_release

And this template https://brain-development.org/brain-atlases/atlases-from-the-dhcp-project/cortical-surface-template/



Slava can help you access the templates
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ecr05** [comment]
Hi Emma - not sure I can help here, I have the same problem with link when trying to access it. Who is maintaining this resource, Imperial? Perhaps, Jelena/Daniel will be a person to ask what’s wrong with this.

Best Wishes,
Slava

On 25 Aug 2024, at 16:23, Emma Robinson ***@***.***> wrote:

It's this one https://github.com/ecr05/dHCP_template_alignment/blob/master/configs/config_subject_to_40_week_template_3rd_release

And this template https://brain-development.org/brain-atlases/atlases-from-the-dhcp-project/cortical-surface-template/



Slava can help you access the templates
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ecr05** [comment]
Yourong, Kaili

Can you send Logan's template to this user.

Tbh there's maybe no point in public sharing as the template needs to change with the next data release (learning-generated surfaces).

Emma

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by trichtu** [comment]
Thanks for helping the connections. If there is any template could be shared, please send to my email: trichtu.gmail.com 
Best,
Liang

**Comment by ecr05** [comment]
Hi All,

The link of dhcp templates:https://github.com/metrics-lab/CorticalAsymmetry/tree/main/Templates/dHCP

Hope it can help.

BW
Kaili
________________________________

**Comment by trichtu** [comment]
Thank you very much. It does help.
